### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by johannct** [airnandez/lsst-cvmfs#1]
1/ The install procedure works with Ubuntu 12.04
2/ As deb or rpm files are "curl"-ed from CERN, it might be useful to have official repositories loaded in the system to get notices of upgrades to CERN VMFS. Do these exist?

**Comment by airnandez** [comment]
Thanks for your confirmation that this works also on Ubuntu 12.04.

Regarding the repositories of the CernVM FS software, according to [this page](http://cernvm.cern.ch/portal/filesystem/downloads) CERN hosts a Yum repository at [http://cvmrepo.web.cern.ch/cvmrepo/yum](http://cvmrepo.web.cern.ch/cvmrepo/yum) which could be used for Linux systems which use Yum. Information for configuring additional Yum repositories to your system can be found in the [RedHat customer portal](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Deployment_Guide/sec-Managing_Yum_Repositories.html).

I'm not aware of a public repository for Ubuntu which maintains an up-to-date CernVM FS package.
