### ISSUE TITLE
Unable to loadLSST.bash on Mac

### ISSUE THREAD

**Issue by rmjarvis** [airnandez/lsst-cvmfs#5]
I followed the instructions for installing on my Mac (10.10.5), and everything seemed successful up until the instruction to run loadLSST.bash:

```
$ source loadLSST.bash 
-bash: /Users/Mike/Astro/lsst/eups/bin/setups.sh: No such file or directory
-bash: setup: command not found
-bash: setup: command not found
```

I guess I need to install eups?  This wasn't mentioned in the installation instructions anywhere as far as I saw.  

Also, looking at this script, it looks like it's going to want to `setup anaconda`.  Am I going to need to install anaconda too?  This can't just use the regular system python?  This should be mentioned in the installation instructions too if this is the case.

**Comment by airnandez** [comment]
Hi Mike,

thanks for your feedback. I'm surprised by the error message you are observing. I confirm that you don't need to install Anaconda nor EUPS nor any other software package: each one of the versions of the LSST stack distributed via this mechanism is self consistent. This means that each version of the LSST stack uses the Python interpreter of the embedded Anaconda installation (which may vary for each version of the stack). It does not use the Python interpreter included in your operating system but the one shipped with Anaconda.

My guess is that there is in your environment a variable `LSST_HOME` which points to `/Users/Mike/Astro/lsst`. My suggestion is to open a new terminal session in which there is no environmental variables starting with `LSST_*` nor `EUPS*` and then do:

```
$ unset LSST_HOME
$ source /cvmfs/lsst.in2p3.fr/software/darwin-x86_64/lsst-v11.0/loadLSST.bash
```

After having successfully sourced `loadLSST.bash` you can know what version of Python you are using with the commands:

```
$ which python
/cvmfs/lsst.in2p3.fr/software/darwin-x86_64/lsst-v11.0/DarwinX86/anaconda/2.2.0/bin/python

$ python --version
Python 2.7.9 :: Anaconda 2.2.0 (64-bit)
```

Hope this helps,

**Comment by rmjarvis** [comment]
> My guess is that there is in your environment a variable LSST_HOME which points to /Users/Mike/Astro/lsst

Yes, you're right.  Looks like I had that in my .bashrc from some old attempt to get the LSST stack installed on my machine.  When I removed that (and restarted the terminal session) it worked properly.  Thanks for your help.
