### ISSUE TITLE
Add lsst-v14.0?

### ISSUE THREAD

**Issue by kadrlica** [airnandez/lsst-cvmfs#9]
Thank you for the very nice tool and distribution. I was wondering if there were plans to add lsst-v14.0?

**Comment by airnandez** [comment]
Hi Alex,

thanks for your feedback. `v14.0` is now available through this distribution mechanism for Linux. The version for macOS will come online later.

**Comment by airnandez** [comment]
`v14.0` for macOS is now also online.

**Comment by kadrlica** [comment]
Great, thanks!
